# Generated by Django 3.1.6 on 2021-02-05 06:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websiteFunctions', '0003_auto_20210204_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='function',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 2, 4, 23, 37, 10, 396439), null=True),
        ),
    ]
