# Generated by Django 3.1.6 on 2021-02-05 14:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websiteFunctions', '0004_auto_20210204_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='function',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 2, 5, 7, 26, 42, 525031), null=True),
        ),
    ]
