# Generated by Django 3.1.4 on 2021-02-06 18:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websiteFunctions', '0005_auto_20210205_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='function',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 2, 6, 11, 2, 21, 389964), null=True),
        ),
    ]
