# Generated by Django 3.1.6 on 2021-02-07 03:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websiteFunctions', '0006_auto_20210206_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='function',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 2, 6, 20, 47, 35, 947703), null=True),
        ),
    ]
